Only pin tenacity to < 5.0.4 for trusty
Ubuntu Lunar uses python 3.11 where tenacity < 5.0.4 fails with:
"AttributeError: module 'asyncio' has no attribute 'coroutine'"

This is because the @asyncio.coroutine has been deprecated since
version 3.8 and was removed in 3.11:
https://docs.python.org/3.10/library/asyncio-task.html#generator-based-coroutines

LP: #2031439